name: mdm_domain
description: Models and generic domain function for the Mini Dungeon Maker
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.5.0

dev_dependencies:
  build_runner: ^2.1.11
  coverage: ^1.1.0
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
