name: mdm_domain

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/mdm_domain.yaml
      - mdm_domain/**

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/mdm_domain.yaml
      - packages/mdm_domain/**

jobs:
  build:
    defaults:
      run:
        working-directory: mdm_domain

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed lib

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run Tests
        run: |
          dart pub global activate coverage 1.2.0
          dart test -j 1 -x pull-request-only --coverage=coverage && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: mdm_domain/coverage/lcov.info
