name: mdm_game

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/mdm_game.yaml
      - packages/mdm_game/**

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/mdm_game.yaml
      - packages/mdm_game/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@main

      - name: Install Dependencies
        run: melos bootstrap

      - name: Format
        run: melos exec --scope mdm_game dart format --set-exit-if-changed lib

      - name: Analyze
        run: melos exec --scope mdm_game dart analyze --fatal-infos --fatal-warnings .

      - name: Run Tests
        run: melos exec --scope mdm_game flutter test --coverage

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: packages/mdm_game/coverage/lcov.info
