name: mdm_server

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/mdm_server.yaml
      - packages/mdm_server/**

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/mdm_server.yaml
      - packages/mdm_server/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@main

      - name: Install Dependencies
        run: melos bootstrap

      - name: Format
        run: melos exec --scope mdm_server dart format --set-exit-if-changed lib

      - name: Analyze
        run: melos exec --scope mdm_server dart analyze --fatal-infos --fatal-warnings .

      - name: Run Tests
        run: |
          flutter pub global activate coverage 1.2.0
          melos exec --scope mdm_server flutter test --coverage && melos exec --scope mdm_server flutter pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: packages/mdm_server/coverage/lcov.info

